import {appendFileSync} from 'node:fs';
import {readFileSync} from 'node:fs';import {spawn} from 'node:child_process';import{createInterface}from'node:readline';import assert from'node:assert/strict';
const{instance:{exports:e}}=await WebAssembly.instantiate(readFileSync(new URL('./public/engine.wasm',import.meta.url)),{}),Q=1n<<24n,MAX=(1n<<64n)-1n;
const v=()=>new BigUint64Array(e.memory.buffer,e.state_ptr(),e.state_words());
const{recipes,resources,rawResources}=JSON.parse(readFileSync(new URL('./public/recipes.json',import.meta.url)));const ri=n=>resources.indexOf(n),bi=n=>recipes.findIndex(x=>x.building===n),si=r=>rawResources.includes(resources[r])?84+rawResources.indexOf(resources[r]):371+r;
function reset(){v().fill(0n);v()[282]=65536n*Q;}function building(n,c=1){v()[bi(n)]=BigInt(c)*Q;}function stock(n,c){v()[si(ri(n))]=BigInt(c)*Q;}const rate=n=>v()[116+bi(n)],draw=n=>v()[451+ri(n)];
const child=spawn(new URL('target/release/production-lab-cu-runner',import.meta.url).pathname,[],{env:{...process.env,RUST_LOG:'error'},stdio:['pipe','pipe','inherit']}),lines=createInterface({input:child.stdout})[Symbol.asyncIterator]();let cases=0,maxCu=0,maxMetadataCu=0;
async function run(action=255){const before=Array.from(v(),String);assert.equal(e.build(action),0,`Wasm case ${cases}`);const after=Array.from(v());if(!process.env.NATIVE_ONLY){child.stdin.write([action,...before].join(' ')+'\n');const result=JSON.parse((await lines.next()).value);assert.equal(result.error,undefined,JSON.stringify({case:cases,...result}));assert.deepEqual(result.state,Array.from(v(),String));if(process.env.CAPTURE_PROFILE)appendFileSync(process.env.CAPTURE_PROFILE,JSON.stringify({case:cases,action,before,totalCu:result.totalCu})+'\n');maxCu=Math.max(maxCu,result.totalCu);maxMetadataCu=Math.max(maxMetadataCu,result.metadataCu);}assert.equal(e.reference(),0);assert.deepEqual(Array.from(v().slice(116,281)),after.slice(116,281),`full/incremental case ${cases}`);v().set(after);let next=MAX;for(let r=0;r<80;r++){let supply=0n,used=0n;for(let i=0;i<84;i++){assert.ok(v()[116+i]<=v()[i]);if(recipes[i].output===resources[r])supply+=v()[116+i];used+=BigInt(recipes[i].inputs.filter(x=>x===resources[r]).length)*v()[116+i];}assert.equal(BigInt.asIntN(64,v()[200+r]),supply-used);assert.equal(v()[451+r],used>supply?used-supply:0n);if(used>supply){assert.ok(v()[si(r)]>0n);const t=v()[si(r)]*Q/(used-supply);if(t<next)next=t;}}assert.equal(v()[280],next);cases++;}
try{
 reset();building('Assembly Plant',5);building('Electronics Fabricator',3);building('Copper Mine',3);building('Silicate Mine',3);stock('Polymers',100);stock('Electronics',10);await run();assert.equal(rate('Assembly Plant'),5n*Q);assert.equal(rate('Electronics Fabricator'),3n*Q);assert.equal(draw('Electronics'),2n*Q);assert.equal(draw('Copper'),0n);assert.equal(v()[280],5n*Q);
 const cached=Array.from(v().slice(531)),rates=Array.from(v().slice(116,280));stock('Electronics',20);await run();assert.deepEqual(Array.from(v().slice(531)),cached);assert.deepEqual(Array.from(v().slice(116,280)),rates);assert.equal(v()[280],10n*Q);
 stock('Electronics',0);await run();assert.equal(rate('Assembly Plant'),3n*Q);assert.equal(draw('Electronics'),0n);
 reset();building('Assembly Plant',5);stock('Electronics',10);stock('Polymers',15);await run();assert.equal(rate('Assembly Plant'),5n*Q);assert.equal(v()[280],2n*Q);
 reset();building('Slaughterhouse',5);building('Ranch',2);building('Soy Farm',2);stock('Livestock',9);await run();assert.equal(rate('Slaughterhouse'),5n*Q);assert.equal(rate('Ranch'),2n*Q);assert.equal(draw('Livestock'),3n*Q);assert.equal(v()[280],3n*Q);
 reset();v().fill(Q,0,84);for(const r of resources)stock(r,10);await run();await run(bi('Copper Mine'));
 for(let r=0;r<80;r++){reset();v().fill(100n*Q,0,84);v()[si(r)]=10n*Q;await run();}
 let seed=91;for(let trial=0;trial<120;trial++){reset();for(let i=0;i<84;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;v()[i]=BigInt((seed>>>16)%5)*Q;}for(let r=0;r<80;r++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;if((seed>>>16)%3===0)v()[si(r)]=10n*Q;}await run();await run(seed%84);v()[282]=BigInt((seed>>>8)%100)*Q;await run(254);}
 console.log(JSON.stringify({cases,maxCu,maxMetadataCu,wasmSbfExactMatch:true}));
}finally{child.stdin.end();child.kill();}
